version: '3'
services:
  nestjs-backend:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: yarn start:prod
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - nestjs-network
    depends_on:
      - postgres
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - nestjs-network

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - nestjs-network

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data:
  postgres-data:
